### ISSUE TITLE
is this being maintained

### ISSUE THREAD

**Issue by sanjayminni** [fortizpenaloza/Willow-Materialize#4]
I am not able to install the package thru Iceberg or Metacello script in Pharo 8 64 bit (windows). 
Seems It cannot find the Baseline of.
it this package being maintained

**Comment by fortizpenaloza** [comment]
Hello, sorry for the late reply. No, it is not. I was reluctant when Google change its aproach with Material Web Components. 

I recommend that you take a look to https://github.com/ba-st/Willow-Bootstrap

**Comment by sanjayminni** [comment]
Thank you.
Would you suggest I stick to bootstrap or something else as of now for a
serious business application where I can't have maintenance headaches

**Comment by fortizpenaloza** [comment]
Yes, we're using Bootstrap in all our business applications. 

It'll be clear for you, after a couple of iterations using Willow, that you will be able to change the component supplier in the future with little or no effort of your side.

**Comment by sanjayminni** [comment]
thank you for your help


---

   -   Sanjay Minni
     +91-9900-902902
